### ISSUE TITLE
Drawer - open / close performance

### ISSUE THREAD

**Issue by jps** [newscorp-ghfb/NewsKit#814] opened 2023-04-06 15:11 UTC
# Describe the bug

@sephram has raised that the opening of the drawer feels a bit slow, we are able to replicate this in the mobile version of the website, it may be hard to see in the video but it's noticeable how long it's taking after clicking the button. 

 https://user-images.githubusercontent.com/350953/230420877-d9f40b87-e73f-4192-8049-ca2a365f749c.mov

# To Reproduce
Steps to reproduce the behaviour:
1. Go to https://newskit.co.uk  
2. Resize to mobile view
3. Open the navigation drawer

# Expected behaviour
Should be quicker 

# Additional Information 
Alan provided some flame graphs which indicate the issue could be in the theme provider

We should also investigate tabs as they mention this in their message. 

## Before

![image](https://user-images.githubusercontent.com/350953/230421789-ac7a99de-908b-4ce6-a006-15bb4cc64f30.png)

## After

![image](https://user-images.githubusercontent.com/350953/230421751-38ae613a-bf60-4559-b603-599c4b803ad3.png)

**Comment by mutebg** [comment] 2023-04-13 11:06
I looked into performance between branches with the optimized theme and without one, I can see 4-5 times speed improvements. My suggestion is to implement #751 first and see if that solves the issue do DJ

**Comment by sephram** [comment] 2023-04-26 17:51
Hello everyone, have been testing newskit@0.0.0-f8544123a on my local and the performance has improved significantly. However when I use NK 7.2.0 the issue is still there (with or without the themeOptions prop)

**Comment by mutebg** [comment] 2023-04-27 02:57
Hi @sephram, version 7.2.0 does not have the `themeOptions` which improves the performance, we are planning to include it in the next release ( 7.3.0  ) but wanted to check first if that solves your issue. That's why we created this alpha release [0.0.0-f8544123a](mailto:newskit@0.0.0-f8544123a) so you can test it first.

Since your confirmation, we will move on and make it part of 7.3.

**Comment by mutebg** [comment] 2023-05-11 09:55
The issue has been resolved in 7.3 v

**Closed by mutebg** 2023-05-11 09:55 UTC
Labels: bug
