### ISSUE TITLE
Weird hover styles applying on elements (NK 7 and newer)

### ISSUE THREAD

**Issue by sephram** [newscorp-ghfb/NewsKit#856] opened 2023-04-26 18:03 UTC
# Describe the bug
On storybook, after upgrading to NK 7 (still happening on version 7.2.0) there are some hover styles being applied to the elements which are not part of our DS. This is not happening if we use Newskit 6.8.0.

# To Reproduce
1. Go to [Factiva DS Storybook](https://jubilant-carnival-new3wpe.pages.github.io/develop/?path=/story/theme-theme-values--borders)
2. Move the mouse over the story elements.
3. See error (if you move to other component stories you can also see the same issue happening)

# Expected behavior
Hover styles should not be applied/overridden.

# Screenshots / Video / Test Environment
https://user-images.githubusercontent.com/10291495/234663149-fa8e17d9-7b74-426a-93bb-e72fb4d43d63.mov

# Desktop (please complete the following information):
 - OS: Mac OS 12.2.1
 - Browser Edge, Chrome
 - Version:  (latest)

**Comment by isuscbrmid** [comment] 2023-05-02 06:05
any news on this?

**Comment by jps** [comment] 2023-05-02 13:31
@sephram  @isuscbrmid 
@Vanals is taking a look to see if he can repo if we can we will be taking this through our Thursday session.

**Comment by Vanals** [comment] 2023-05-02 13:40
Hi!

I had a quick look with @mutebg. 

From what we could see, it is not something happening in our storybook, and we do not have such global styles in our components.

From what we can see looks like you have some global styling applied to any element which gives white background on `hover and if not disabled`.
![Screenshot 2023-05-02 at 14 20 15](https://user-images.githubusercontent.com/25549355/235678456-22e2c85e-7e5b-493a-aa7d-54c43abb5954.png)

The link was helpful but in order to debug it we would need a `reproduction` of the issue in a codepen,  for instance! For now we can't really see it being a bug coming from Newskit.


If you could check out in your repo where those styles may be coming from and reproduce the bug, it would be helpful!
But let us know if you may have more insight we could investigate on.

Thank you.

**Comment by sephram** [comment] 2023-05-02 16:33
Hello @Vanals, do you know if style presets format for the `TextField` component changed? Asking because removing the [hover  custom stylings](https://github.com/newscorp-ghfb/factiva-design-system/blob/develop/src/themes/stylePresets/textField.js#L22)  seems to fix the issue, but it will impact the component look.  Also, this is not happening on NK 6.8, can you share an example of the new stylePresets for the `TextField`

**Comment by Vanals** [comment] 2023-05-03 09:03
Hi @sephram !

Yes, we did consider you saying in NK 6.8 it was working but it may be due to how you implemented Newskit. 
We can see for instance that you do have some workaround such as

```
    // Workaround, since the disabled placeholder color was not being applied
    '& input:disabled::placeholder': {
      color: '{{colors.inkNonEssential}}',
    },
 ```
 
And anyway we see that you use selectors within the CSS state keys(base, hover, etc.) which are not supposed to be there. Only CSS property is a scenario we safely handle. The rest is a bit unknown, typescript would have flagged such practice.
 
We believe some not standard practices may be breaking your CSS.
We think you should get a more clear understanding of what is going on on your side, and again if you can provide a reproduction of the bug in isolation even better, but to us so far seems coming from your implementation and not a Newskit bug itself, and is really hard to spot for us.

About any changes in Text Field you can find the defaults of the TextField here:  https://github.com/newscorp-ghfb/NewsKit/blob/main/src/text-field/defaults.ts.
Clicking on `history` you can see what may have changed in the previous versions, also please check the [release notes](https://github.com/newscorp-ghfb/NewsKit/releases), which may help you.

Same for the Style preset: https://github.com/newscorp-ghfb/NewsKit/blob/main/src/theme/presets/style-presets.ts

Let us know if you find out anything 👍 , or have any more clues.

**Comment by Daniel-M-V** [comment] 2023-05-04 15:01
Hi @Vanals,

I was checking if removing the "workaround" selectors actually fixed the issue, but it seems the selectors present in the state-keys seem to be unrelated to the bug.

I was however able to determine that there is some relation between the `color` property in the `base-state-key` object and the `hover-state-key` object. Attached image shows the minimum needed to trigger the hover bug.

<img width="699" alt="Screen Shot 2023-05-04 at 08 31 12" src="https://user-images.githubusercontent.com/86614425/236244926-6a806ebc-815a-4e36-9df1-e10ed501eab9.png">

Hope this helps pinpoint the issue.

**Comment by mutebg** [comment] 2023-05-05 05:10
@Daniel-M-V The issue is from the triple curly bracket after color.inkBase `}}}`, our parser handles only 2 of these, which means  1 bracket is left inside the CSS, and works like closing bracket for the selector.

**Comment by Daniel-M-V** [comment] 2023-05-05 13:27
Hi @mutebg,
I think that triple curly-bracket was indeed the cause of the problem.
Odd how no one noticed that before now... 😅. Thank you.

I tested briefly by correcting the triple bracket and it seems to fix the issue. 
Hope someone else can confirm it before closing this.

**Closed** 2023-07-05 05:58 UTC
Labels: bug
